services:
  - type: web
    name: EcomBackend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 4000
    healthCheckPath: /health
    plan: free